# Generated by Django 5.2.7 on 2025-10-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='code',
            new_name='otp',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='otp',
        ),
    ]
